import type { FC } from 'react';

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'https://www.veloura.ai';

export const COMMUNITY_FAQ = [
  {
    q: 'What is the Veloura.ai community feed?',
    a: 'A real-time feed of AI-generated art, photos, and videos made by real users on Veloura.ai. Browse images and clips across every style — photoreal, anime, cinematic, NSFW — click any post to see the full prompt, model, and settings used.',
  },
  {
    q: 'Can I see the prompts and settings behind each post?',
    a: 'Yes. Tap any community post to open it and view the prompt, negative prompt, checkpoint, LoRAs, sampler, steps, CFG scale, seed, and resolution. Every detail is one click away, so you can remix, learn from, or reproduce the output.',
  },
  {
    q: 'Is NSFW content visible in the community feed?',
    a: 'NSFW and adult art is supported for adult users. You control whether NSFW posts appear in your feed with the NSFW toggle in Settings — default respects your account age gate and regional preferences.',
  },
  {
    q: 'Can I share my own AI art to the community?',
    a: 'Yes. Any image or video you generate can be published to the community feed with one click. You own what you create — sharing is optional, and you can delete any post anytime.',
  },
  {
    q: 'How are posts ranked in the feed?',
    a: 'The feed blends recency with engagement. New posts surface quickly; posts that get views, likes, and remixes stay higher longer. Feeds are personalized over time based on what you engage with.',
  },
  {
    q: 'Does the community feed allow video posts?',
    a: 'Yes. Image posts, video clips, and animated outputs from AI video generation, motion transfer, and face swap all appear together in the feed. Videos auto-preview on hover and play full in the viewer modal.',
  },
];

const FEATURES = [
  { title: 'Mixed Feed of AI Art & Video', body: 'Images, animated clips, and video posts all in one masonry feed — generated by real Veloura.ai users.' },
  { title: 'See the Prompt', body: 'Tap any post to see the full prompt, negative prompt, model, LoRAs, and generation settings used to make it.' },
  { title: 'Remix in One Click', body: 'Like a post? Send the exact prompt and settings to the generator and remix it with your own twist.' },
  { title: 'NSFW & SFW', body: 'Adult users can opt into NSFW posts; SFW-only users get a clean feed. You control what you see.' },
  { title: 'Discover Top Models', body: 'Trending checkpoints and LoRAs surface through the feed. See what styles are performing this week.' },
  { title: 'No Algorithm Rot', body: 'The feed blends recency and engagement — no shadowban, no opaque algorithm penalties.' },
];

const CommunitySeoBlock: FC = () => {
  const softwareSchema = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Veloura.ai Community',
    applicationCategory: 'SocialNetworkingApplication',
    operatingSystem: 'Web',
    url: `${APP_URL}/community`,
    description:
      'Share and discover AI-generated art, NSFW AI images, and AI videos made by real users. Uncensored AI art community — no restrictions, full prompts, one-click remix.',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.9', ratingCount: '3410' },
  };

  const faqSchema = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: COMMUNITY_FAQ.map((item) => ({
      '@type': 'Question',
      name: item.q,
      acceptedAnswer: { '@type': 'Answer', text: item.a },
    })),
  };

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: APP_URL },
      { '@type': 'ListItem', position: 2, name: 'Community', item: `${APP_URL}/community` },
    ],
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      <section className="mt-12 border-t border-white/10 pt-10">
        <div className="mx-auto max-w-4xl space-y-10">
          <div>
            <h2 className="text-2xl font-bold text-white md:text-3xl">
              Share &amp; Discover Uncensored AI Art, NSFW Images &amp; AI Videos
            </h2>
            <p className="mt-4 text-[0.95rem] leading-relaxed text-text-secondary">
              The Veloura.ai community is a real-time feed of AI art, NSFW images, and AI-generated videos
              created by real users. See what the world is making, click any post to view the exact prompt and model,
              remix in one tap, or publish your own creations. No algorithm gatekeeping, no shadowbans, no forced
              filters — just a creative community built for adults who want full expressive control.
            </p>
          </div>

          <div className="grid gap-5 md:grid-cols-2">
            {FEATURES.map((f) => (
              <div key={f.title} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5">
                <h3 className="text-base font-semibold text-white">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-text-secondary">{f.body}</p>
              </div>
            ))}
          </div>

          <div>
            <h2 className="text-2xl font-bold text-white md:text-3xl">Frequently Asked Questions</h2>
            <div className="mt-5 space-y-4">
              {COMMUNITY_FAQ.map((item) => (
                <details key={item.q} className="group rounded-2xl border border-white/10 bg-white/[0.03] p-5">
                  <summary className="cursor-pointer list-none text-base font-semibold text-white marker:hidden">
                    {item.q}
                  </summary>
                  <p className="mt-3 text-sm leading-relaxed text-text-secondary">{item.a}</p>
                </details>
              ))}
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default CommunitySeoBlock;
