import FAQSchema from '@/components/seo/FAQSchema';

const FAQ_ITEMS = [
  { q: 'Is the AI music generator free?', a: 'Yes, it is free on Veloura.ai. Premium plans unlock longer tracks, higher quality audio, and more generations.' },
  { q: 'What prompt tips work best?', a: 'Include genre, mood, tempo, and instruments. Example: "relaxing lofi hip-hop, slow tempo, piano and soft drums, warm atmosphere".' },
  { q: 'Are the generated tracks fully original?', a: 'Yes. Every track is uniquely generated by the AI — not sampled or copied from existing music.' },
  { q: 'What genres can the AI generate?', a: 'The AI supports a wide range including lofi, cinematic, electronic, classical, jazz, ambient, and more.' },
  { q: 'Can I use the music in my videos or projects?', a: 'Premium plans include commercial usage rights for generated music. Check your plan for full licensing details.' },
];

export default function MusicGenerationSEOContent() {
  return (
    <section className="mt-20 pb-16">
      <FAQSchema items={FAQ_ITEMS} />
      <div className="mb-14 border-t border-white/10" />

      <div className="mb-14">
        <h2 className="text-2xl font-bold text-white">What is the AI Music Generator?</h2>
        <p className="mt-5 max-w-3xl text-base leading-relaxed text-white/60">
          The AI Music Generator creates original instrumental music from text prompts — no
          instruments, no music theory required. Describe the mood, genre, tempo, and style you
          want, and the AI composes and produces a full instrumental track in seconds. Perfect for
          background music, videos, games, and creative projects.
        </p>
      </div>

      <div className="mb-14">
        <h2 className="text-2xl font-bold text-white">How Does the AI Music Generator Work?</h2>
        <div className="mt-6 grid gap-4 sm:grid-cols-3">
          {[
            { step: '01', title: 'Describe Your Music', desc: 'Enter a text prompt describing the style, mood, tempo, and instruments you want.' },
            { step: '02', title: 'AI Composes the Track', desc: 'The AI generates an original instrumental track matching your description in seconds.' },
            { step: '03', title: 'Download Your Music', desc: 'Download your AI-generated music as a high-quality audio file ready to use.' },
          ].map(({ step, title, desc }) => (
            <div key={step} className="rounded-2xl border border-white/10 bg-[#12121a] p-5">
              <span className="text-3xl font-black text-[#ff3e8a]/30">{step}</span>
              <h3 className="mt-2 text-base font-semibold text-white">{title}</h3>
              <p className="mt-1 text-sm leading-relaxed text-white/50">{desc}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="mb-14">
        <h2 className="text-2xl font-bold text-white">What Can You Create with AI Music Generator?</h2>
        <ul className="mt-6 grid gap-3 sm:grid-cols-2">
          {[
            'Background music for YouTube videos and reels',
            'Game soundtracks and ambient audio',
            'Relaxing lofi or ambient music for focus',
            'Cinematic scores for short films and presentations',
            'Custom music for AI character or companion experiences',
            'Original beats and instrumentals for any project',
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5 rounded-xl border border-white/10 bg-[#12121a] px-4 py-3">
              <span className="mt-0.5 h-2 w-2 shrink-0 rounded-full bg-[#ff3e8a]" />
              <span className="text-sm text-white/60">{item}</span>
            </li>
          ))}
        </ul>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-white">Frequently Asked Questions</h2>
        <div className="mt-6 space-y-3">
          {FAQ_ITEMS.map(({ q, a }) => (
            <details key={q} className="group rounded-2xl border border-white/10 bg-[#12121a]">
              <summary className="flex cursor-pointer list-none items-center justify-between px-5 py-4 text-sm font-semibold text-white select-none marker:hidden">
                {q}
                <span className="ml-4 shrink-0 text-[#ff3e8a] transition-transform duration-200 group-open:rotate-45">+</span>
              </summary>
              <p className="border-t border-white/10 px-5 py-4 text-sm leading-relaxed text-white/50">{a}</p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}
