"use client"

import Image from "next/image"
import { ArrowUpRight, Check, Sparkles } from "lucide-react"

const routeData = {
  companions: { eyebrow: "01 / COMPANIONS", title: "A presence made for your frequency.", body: "Create an adult companion with memory, voice, visual identity, and a personality that becomes more yours with every conversation.", image: "/veloura-companion.png", points: ["Persistent memory", "Custom personality", "Voice and image replies", "Private by default"] },
  image: { eyebrow: "02 / IMAGE STUDIO", title: "Make the scene feel real.", body: "A cinematic workspace for expressive characters, intimate worlds, editorial portraits, and every idea between the lines.", image: "/veloura-create.png", points: ["Prompt to image", "Remix and inpaint", "Upscale in high resolution", "Switch models instantly"] },
  video: { eyebrow: "03 / MOTION LAB", title: "Give the still a pulse.", body: "Direct short scenes from a prompt or image. Shape the camera, movement, rhythm, and atmosphere of every frame.", image: "/veloura-hero.png", points: ["Image to video", "Text to video", "Motion presets", "HD exports"] },
  audio: { eyebrow: "04 / VOICE ATELIER", title: "Let the story speak.", body: "Layer expressive character voices and sound into the worlds you are already building.", image: "/veloura-hero.png", points: ["Character voices", "Voice styling", "Audio generation", "Private projects"] },
  roleplay: { eyebrow: "05 / ROLEPLAY ROOMS", title: "Step into the scene.", body: "Create immersive rooms with your own rules, characters, tone, and narrative momentum.", image: "/veloura-companion.png", points: ["Scenario builder", "Persistent context", "Multiple characters", "Scene controls"] },
  apps: { eyebrow: "06 / THE STUDIO", title: "Everything has a room.", body: "Explore the connected creative system: companions, image, video, audio, roleplay, models, and training.", image: "/veloura-create.png", points: ["One private workspace", "Connected tools", "Model library", "Creator controls"] },
} as const

export function ExperiencePage({ kind }: { kind: keyof typeof routeData }) {
  const data = routeData[kind]
  return <main className="veloura-shell"><div className="grain" aria-hidden="true" /><header className="site-header"><a href="/" className="wordmark"><span className="wordmark-dot" />veloura<span>/ai</span></a><nav className="site-nav"><a href="/ai-apps">Discover</a><a href="/ai-image-generator-no-filter">Create</a><a href="/ai-girlfriend-chat">Companions</a><a href="/ai-roleplay">Roleplay</a></nav><div className="header-actions"><a href="/login" className="quiet-link">Log in</a><a href="/register" className="header-button">Enter studio <ArrowUpRight size={15} /></a></div></header><section className="new-hero"><div className="hero-copy-new"><p className="eyebrow"><span /> 18+ creative space</p><p className="section-index">{data.eyebrow}</p><h1>{data.title}</h1><p className="hero-lede">{data.body}</p><div className="hero-actions"><a className="button-primary" href="/register">Open workspace <ArrowUpRight size={17} /></a><a className="play-link" href="/ai-apps"><span><Sparkles size={13} /></span> Explore tools</a></div></div><div className="hero-visual"><Image src={data.image} alt="" fill priority sizes="(max-width: 800px) 100vw, 50vw" /><div className="hero-visual-overlay" /><div className="hero-caption"><span>{data.eyebrow}</span><span>PRIVATE PREVIEW</span></div></div></section><section className="module-section"><div className="section-index">WHAT&apos;S INSIDE</div><div className="module-grid">{data.points.map((point, index) => <article className="module-card" key={point}><div className="module-copy"><p className="section-index">0{index + 1}</p><h3>{point}</h3><p>Designed to stay fluid, expressive, and completely under your control.</p><span><Check size={15} /> Included in your studio</span></div></article>)}</div></section><section className="final-cta"><p className="eyebrow"><span /> Make it yours</p><h2>Open the<br /><i>next room.</i></h2><a className="button-primary" href="/register">Start free <ArrowUpRight size={17} /></a></section><footer className="site-footer"><a href="/" className="wordmark"><span className="wordmark-dot" />veloura<span>/ai</span></a><span>© 2026 Veloura. Made for imagination.</span><div><a href="/ai-apps">Studio</a><a href="/login">Account</a></div></footer></main>
}
