"use client"

import { ArrowRight, Check, Sparkles, Wand2 } from "lucide-react"

const routeData: Record<string, { eyebrow: string; title: string; description: string; features: string[] }> = {
  companions: { eyebrow: "01 / AI companions", title: "A presence that feels personal.", description: "Build an expressive adult companion with memory, voice, personality, and a visual identity that evolves with every conversation.", features: ["Long-term memory", "Custom personalities", "Voice and image replies", "Private by default"] },
  image: { eyebrow: "02 / Image studio", title: "Turn a thought into a scene.", description: "A cinematic image workspace for expressive characters, intimate worlds, editorial portraits, and every idea between the lines.", features: ["Prompt-to-image", "Image remixing", "Inpainting and upscale", "Multiple model styles"] },
  video: { eyebrow: "03 / Motion lab", title: "Give your imagination a pulse.", description: "Animate stills, direct short scenes, and shape movement with an AI video suite made for creators who want more control.", features: ["Image-to-video", "Text-to-video", "Motion presets", "HD exports"] },
  audio: { eyebrow: "04 / Voice atelier", title: "Let the story speak.", description: "Explore expressive voice, sound design, and character audio for conversations, scenes, and private creative projects.", features: ["Character voices", "Voice styling", "Audio generation", "Private projects"] },
  roleplay: { eyebrow: "05 / Roleplay rooms", title: "Step into the scene.", description: "Create immersive rooms with your own rules, characters, tone, and narrative momentum. The only limit is what you want to explore.", features: ["Scenario builder", "Persistent context", "Multiple characters", "Scene controls"] },
}

export function ExperiencePage({ kind }: { kind: keyof typeof routeData }) {
  const data = routeData[kind]
  return <main className="app-shell"><div className="noise" aria-hidden="true" /><header className="topbar"><a className="brand" href="/"><span className="brand-mark">◈</span> veloura<span>.ai</span></a><nav className="nav open"><a href="/ai-apps">Explore</a><a href="/ai-image-generator-no-filter">Create</a><a href="/ai-girlfriend-chat">Companions</a><a href="/ai-roleplay">Roleplay</a></nav><div className="top-actions"><a className="login" href="/login">Log in</a><a className="small-cta" href="/register">Start free <ArrowRight size={15} /></a></div></header><section className="hero route-hero"><div className="hero-grid" /><div className="hero-copy"><div className="pill"><span /> 18+ creative space</div><div className="section-kicker">{data.eyebrow}</div><h1>{data.title}</h1><p>{data.description}</p><div className="hero-buttons"><a className="primary" href="/register">Open workspace <ArrowRight size={18} /></a><a className="secondary" href="/ai-apps"><Sparkles size={15} /> Explore tools</a></div></div><div className="hero-card route-card"><div className="card-top"><span className="live"><span /> PRIVATE PREVIEW</span><span>VEL / 01</span></div><div className="portrait"><div className="portrait-ring" /><div className="portrait-glow" /><span className="portrait-label"><Wand2 size={24} /><br /><b>make it yours</b></span></div><div className="card-bottom"><span>Built for your<br /><b>private imagination.</b></span><ArrowRight /></div></div></section><section className="section route-features"><div className="section-kicker">What&apos;s inside</div><div className="feature-grid">{data.features.map((feature, index) => <article className="tool-card" key={feature}><div className="tool-art"><span>0{index + 1}</span><Sparkles size={20} /></div><div className="tool-body"><h3>{feature}</h3><p>Designed to stay fluid, expressive, and completely under your control.</p><a href="/register">Try it <ArrowRight size={15} /></a></div></article>)}</div></section><section className="section manifesto route-cta"><div className="section-kicker">A softer kind of freedom</div><div className="manifesto-line">Make room<br /><em>for more.</em></div><p>Start with a free workspace, then shape the experience around whatever you want to create.</p><a className="primary" href="/register">Create your account <ArrowRight size={18} /></a></section><footer><a className="brand" href="/"><span className="brand-mark">◈</span> veloura<span>.ai</span></a><span>© 2026 Veloura / Made for imagination.</span><div><a href="/ai-apps">Explore</a><a href="/faq">FAQ</a><a href="/contact">Contact</a></div></footer></main>
}
